export const sampleEvents = [
  {
    id: 1,
    title: 'Midnight City Run',
    date: 'Fri, Aug 23',
    time: '7:30 PM',
    location: 'Downtown Track',
    category: 'Fitness',
    price: '$28',
    image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=80',
    host: 'City Pulse Studio',
    description: 'A neon-lit evening run with guided pacing, music, and post-race recovery zones.',
  },
  {
    id: 2,
    title: 'Design & Coffee Meetup',
    date: 'Sat, Aug 24',
    time: '10:00 AM',
    location: 'North Loft',
    category: 'Networking',
    price: '$15',
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=900&q=80',
    host: 'Creative Circle',
    description: 'Meet designers, founders, and creatives for a collaborative coffee-and-ideas session.',
  },
  {
    id: 3,
    title: 'Summer Sunset Festival',
    date: 'Sun, Aug 25',
    time: '6:00 PM',
    location: 'Harbor Park',
    category: 'Music',
    price: '$45',
    image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=900&q=80',
    host: 'Harbor Live',
    description: 'A waterfront music festival featuring indie acts, food stalls, and sunset DJ sets.',
  },
  {
    id: 4,
    title: 'Startup Pitch Night',
    date: 'Tue, Aug 27',
    time: '7:00 PM',
    location: 'Launch Hub',
    category: 'Business',
    price: '$35',
    image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=900&q=80',
    host: 'Founders Forum',
    description: 'Young founders pitch their next big idea to investors, mentors, and community partners.',
  },
  {
    id: 5,
    title: 'Wellness Yoga Flow',
    date: 'Wed, Aug 28',
    time: '8:30 AM',
    location: 'Sky Garden',
    category: 'Wellness',
    price: '$20',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=900&q=80',
    host: 'Bloom Collective',
    description: 'A calming sunrise yoga class led by experienced instructors in an open-air garden.',
  },
  {
    id: 6,
    title: 'Open Air Cinema',
    date: 'Fri, Aug 30',
    time: '8:15 PM',
    location: 'Riverside Lawn',
    category: 'Culture',
    price: '$18',
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=900&q=80',
    host: 'Luma Events',
    description: 'Bring a blanket and enjoy a curated outdoor screening under the stars.',
  },
  // Fitness
  {
    id: 7,
    title: 'CrossFit Competition 2024',
    date: 'Sat, Aug 31',
    time: '9:00 AM',
    location: 'Sports Arena',
    category: 'Fitness',
    price: '$40',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=80',
    host: 'Elite Fitness Co',
    description: 'High-intensity competition featuring top CrossFit athletes battling for prizes.',
  },
  {
    id: 8,
    title: 'Pilates & Brunch',
    date: 'Sun, Sep 1',
    time: '10:30 AM',
    location: 'Studio Zen',
    category: 'Fitness',
    price: '$32',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=900&q=80',
    host: 'Zen Wellness',
    description: 'Low-impact pilates session followed by a healthy brunch with friends.',
  },
  {
    id: 9,
    title: 'Morning Cycling Tour',
    date: 'Mon, Sep 2',
    time: '7:00 AM',
    location: 'Riverside Path',
    category: 'Fitness',
    price: '$15',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=80',
    host: 'Cycle City Club',
    description: 'Scenic 20-mile bike tour through nature trails with water and snack stops.',
  },
  // Networking
  {
    id: 10,
    title: 'Tech Leaders Roundtable',
    date: 'Tue, Sep 3',
    time: '6:00 PM',
    location: 'Innovation Hub',
    category: 'Networking',
    price: '$25',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=900&q=80',
    host: 'Tech Community',
    description: 'Intimate discussion with industry leaders on emerging technologies and trends.',
  },
  {
    id: 11,
    title: 'Women in Tech Mixer',
    date: 'Wed, Sep 4',
    time: '5:30 PM',
    location: 'Downtown Lounge',
    category: 'Networking',
    price: '$20',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=900&q=80',
    host: 'Women Leaders Network',
    description: 'Connect with inspiring women in tech over drinks and appetizers.',
  },
  {
    id: 12,
    title: 'Marketing Professionals Happy Hour',
    date: 'Thu, Sep 5',
    time: '6:00 PM',
    location: 'Rooftop Bar',
    category: 'Networking',
    price: '$18',
    image: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=900&q=80',
    host: 'Marketing Guild',
    description: 'Network with fellow marketers, discuss campaigns, and make new connections.',
  },
  // Music
  {
    id: 13,
    title: 'Jazz Night at the Conservatory',
    date: 'Fri, Sep 6',
    time: '8:00 PM',
    location: 'Grand Conservatory',
    category: 'Music',
    price: '$50',
    image: 'https://images.unsplash.com/photo-1511379938547-c1f69b13d835?auto=format&fit=crop&w=900&q=80',
    host: 'Conservatory Events',
    description: 'Live jazz performance from award-winning musicians in an intimate setting.',
  },
  {
    id: 14,
    title: 'Indie Rock Showcase',
    date: 'Sat, Sep 7',
    time: '9:00 PM',
    location: 'The Underground Club',
    category: 'Music',
    price: '$22',
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=900&q=80',
    host: 'Local Music Collective',
    description: 'Discover emerging indie bands at this underground venue with great vibes.',
  },
  {
    id: 15,
    title: 'Classical Symphony Orchestra',
    date: 'Sun, Sep 8',
    time: '7:30 PM',
    location: 'Concert Hall',
    category: 'Music',
    price: '$65',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=900&q=80',
    host: 'City Orchestra',
    description: 'Experience the beauty of classical music with the renowned City Orchestra.',
  },
  // Business
  {
    id: 16,
    title: 'Leadership Summit 2024',
    date: 'Mon, Sep 9',
    time: '8:00 AM',
    location: 'Convention Center',
    category: 'Business',
    price: '$99',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=900&q=80',
    host: 'Business Excellence',
    description: 'Two-day summit featuring keynotes from Fortune 500 CEOs and industry experts.',
  },
  {
    id: 17,
    title: 'Personal Finance Workshop',
    date: 'Tue, Sep 10',
    time: '6:00 PM',
    location: 'Financial Center',
    category: 'Business',
    price: '$30',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=900&q=80',
    host: 'Financial Advisors Group',
    description: 'Learn investment strategies, budgeting, and wealth building from experts.',
  },
  // Wellness
  {
    id: 18,
    title: 'Meditation & Mindfulness Retreat',
    date: 'Sat, Sep 14',
    time: '9:00 AM',
    location: 'Mountain Retreat Center',
    category: 'Wellness',
    price: '$120',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=900&q=80',
    host: 'Serenity Wellness',
    description: 'Full-day wellness retreat with meditation, breathing exercises, and nature walks.',
  },
  {
    id: 19,
    title: 'Nutrition & Cooking Class',
    date: 'Wed, Sep 11',
    time: '5:00 PM',
    location: 'Culinary Studio',
    category: 'Wellness',
    price: '$55',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=80',
    host: 'Health Kitchen Academy',
    description: 'Learn to cook nutritious meals from a certified nutritionist and chef.',
  },
  // Culture
  {
    id: 20,
    title: 'Modern Art Exhibition Opening',
    date: 'Thu, Sep 12',
    time: '6:00 PM',
    location: 'Contemporary Art Gallery',
    category: 'Culture',
    price: '$12',
    image: 'https://images.unsplash.com/photo-1549887534-f2b2fb7fb8e7?auto=format&fit=crop&w=900&q=80',
    host: 'City Art Gallery',
    description: 'Celebrate contemporary artists with live performances and artist meet-and-greet.',
  },
  {
    id: 21,
    title: 'Shakespeare in the Park',
    date: 'Fri, Sep 13',
    time: '7:00 PM',
    location: 'Central Park Amphitheater',
    category: 'Culture',
    price: '$0',
    image: 'https://images.unsplash.com/photo-1501612780-7a1fada519e1?auto=format&fit=crop&w=900&q=80',
    host: 'Theater Arts Society',
    description: 'Free outdoor performance of Hamlet by professional theater company.',
  },
];
